version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  codestyle:
    docker:
      - image: python:3.6
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run:
          name: Install flake8
          command: pip3 install flake8
      - run:
          name: Lint with flake8
          command: |
            flake8 --exclude "" --ignore=E501,F821 geotrek/settings
            flake8 geotrek
      - run:
          name: Check no SRID value in migration files
          command: test $(ls geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID | wc -l) -eq 0

  doc:
    docker:
      - image: python:3.6
    environment:
      LANG: C.UTF-8
    working_directory: ~/project/docs
    steps:
      - checkout
      - run:
          name: Install Sphinx
          command: |
            cd docs/
            pip install -r ./requirements.txt
      - run:
          name: Build documentation
          command: |
            cd docs/
            make html

  docker_image:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build docker image base on Ubuntu 20.04
          command: BASE_IMAGE_TAG=focal-3.8 make build
      - run:
          name: Tag and save docker image
          command: |
            docker tag geotrek:latest geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID
            docker save -o ./20.04.$CIRCLE_WORKFLOW_ID.tar geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID
      - persist_to_workspace:
          root: .
          paths:
            - 20.04.*.tar

    resource_class: large

  docker_image_18_04:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Build docker image base on Ubuntu 18.04
          command: BASE_IMAGE_TAG=bionic-3.6 make build
      - run:
          name: Tag and save docker image
          command: |
            docker tag geotrek:latest geotrekce/circleci-admin:18.04-$CIRCLE_WORKFLOW_ID
            docker save -o ./18.04.$CIRCLE_WORKFLOW_ID.tar geotrekce/circleci-admin:18.04-$CIRCLE_WORKFLOW_ID
      - persist_to_workspace:
          root: .
          paths:
            - 18.04.*.tar
    resource_class: large

  docker_test:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare environment
          command: |
            cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
            docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
      - run:
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/20.04.$CIRCLE_WORKFLOW_ID.tar
            docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
      - run:
          name: Check pending migrations
          command: docker-compose run web ./manage.py makemigrations --check
      - run:
          name: Prepare tests
          command: docker-compose run web update.sh
      - run:
          name: Run tests & export coverage
          command: |
            docker-compose run -e ENV=tests web coverage run ./manage.py test -v 2
            docker-compose run web coverage xml -o var/coverage.xml
      - codecov/upload:
          file: var/coverage.xml
          flags: test
          when: on_success
    resource_class: large

  docker_test_18_04:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare environment
          command: |
            cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
            docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
      - run:
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/18.04.$CIRCLE_WORKFLOW_ID.tar
            docker tag geotrekce/circleci-admin:18.04-$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
      - run:
          name: Prepare tests
          command: docker-compose run web update.sh
      - run:
          name: Run tests
          command: |
            docker-compose run -e ENV=tests web coverage run ./manage.py test -v 2
    resource_class: large

  docker_test_nds:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare environment
          command: |
            cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
            docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
      - run:
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/20.04.$CIRCLE_WORKFLOW_ID.tar
            docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
      - run:
          name: Prepare tests
          command: docker-compose run web update.sh
      - run:
          name: Run tests & export coverage
          command: |
            docker-compose run -e ENV=tests_nds web coverage run ./manage.py test -v 2
            docker-compose run web coverage xml -o var/coverage.xml
      - codecov/upload:
          file: var/coverage.xml
          flags: test_nds
          when: on_success
    resource_class: large

  docker_test_nds_18_04:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare environment
          command: |
            cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
            docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
      - run:
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/18.04.$CIRCLE_WORKFLOW_ID.tar
            docker tag geotrekce/circleci-admin:18.04-$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
      - run:
          name: Prepare tests
          command: docker-compose run web update.sh
      - run:
          name: Run tests
          command: |
            docker-compose run -e ENV=tests_nds web coverage run ./manage.py test -v 2

    resource_class: large

  docker_test_js:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare environment
          command: |
            cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
            docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
      - run:
          name: Load docker image
          command: |
            docker load -i /tmp/workspace/20.04.$CIRCLE_WORKFLOW_ID.tar
            docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
      - run:
          name: Prepare tests
          command: |
            sudo apt-get update -q && sudo apt-get install -q -y npm
            docker run geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID ./manage.py collectstatic --noinput
            sudo npm install geotrek/jstests
      - run:
          name: Launch tests
          command: sudo ./node_modules/.bin/mocha-phantomjs geotrek/jstests/index.html
    resource_class: large

  docker_test_integration:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          cp .env-prod.dist .env; cp docker-compose-prod.yml docker-compose.yml
          echo 'LANGUAGES=en fr' >> .env
          echo 'LANGUAGE_CODE=en' >> .env
          mkdir -p var/conf/
          cp cypress/custom.py var/conf/custom.py
          docker run -p 5432:5432 --env-file .env -d postgis/postgis:11-2.5
          docker load -i /tmp/workspace/20.04.$CIRCLE_WORKFLOW_ID.tar
          docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
          docker-compose run web update.sh
          sudo apt-get update -q && sudo apt-get install -q -y npm nginx
          mkdir -p var/conf/extra_static
          make load_data
          make load_test_integration
          docker-compose up -d
          sudo mkdir /var/www/geotrek -p
          sudo ln -s /home/circleci/project/var/media /var/www/geotrek
          sudo ln -s /home/circleci/project/var/static /var/www/geotrek
          sudo ln -s /home/circleci/project/cypress/nginx.conf /etc/nginx/sites-enabled/geotrek.conf
          sudo ls -l /home/circleci/project
          sudo ls -l /var/www/geotrek
          sudo rm /etc/nginx/sites-enabled/default
          sudo nginx -s reload
      - run:
          command: |
            cd /home/circleci/project/cypress
            npm ci
            ./node_modules/.bin/cypress run --record --key 64a5a9b3-9869-4a2f-91e4-e3cd27c2f564

      - store_artifacts:
          path: /home/circleci/project/cypress/videos/
          destination: cypress-videos
      - store_artifacts:
          path: /home/circleci/project/cypress/screenshots/
          destination: cypress-screenshots
    resource_class: large

  docker_publish:
    machine:
      image: ubuntu-2004:202201-02
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          docker load -i /tmp/workspace/20.04.$CIRCLE_WORKFLOW_ID.tar
          docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:$(cat VERSION)
          docker tag geotrekce/circleci-admin:$CIRCLE_WORKFLOW_ID geotrekce/admin:latest
          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
          docker push geotrekce/admin:$(cat VERSION)
          docker push geotrekce/admin:latest
    resource_class: large

  ubuntu_package:
    docker:
      - image: ubuntu:focal
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run: grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' VERSION || sed -i
          's/+dev/.ubuntu20.04+dev<< pipeline.number >>/' debian/changelog
      - run: sed -i 's/geotrek-admin (\([0-9]\+\.[0-9]\+\.[0-9]\+\)\(.*\))
          RELEASED;/geotrek-admin (\1.ubuntu20.04\2) bionic;/' debian/changelog
      - run: apt-get update -q
      - run: DEBIAN_FRONTEND=noninteractive apt-get install -q -y
          software-properties-common
      - run: add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
      - run: apt-get install -q -y dpkg-dev debhelper dh-virtualenv git python3
          python3-venv python3-dev libgdal-dev libffi-dev libxml2-dev
          libxslt1-dev
      - run: dpkg-buildpackage -uc -us -b
      - persist_to_workspace:
          root: /root
          paths: geotrek-admin_*_amd64.deb
    resource_class: large

  ubuntu_package_18_04:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run: grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' VERSION || sed -i
          's/+dev/.ubuntu18.04+dev<< pipeline.number >>/' debian/changelog
      - run: sed -i 's/geotrek-admin (\([0-9]\+\.[0-9]\+\.[0-9]\+\)\(.*\))
          RELEASED;/geotrek-admin (\1.ubuntu18.04\2) focal;/' debian/changelog
      - run: apt-get update -q && apt-get install -q -y dpkg-dev debhelper dh-virtualenv
          git python3 python3-venv python3-dev libgdal-dev libffi-dev
          libxml2-dev libxslt1-dev
      - run: dpkg-buildpackage -uc -us -b
      - persist_to_workspace:
          root: /root
          paths: geotrek-admin_*_amd64.deb
      - store_artifacts:
          path: geotrek-admin_*_amd64.deb
          destination: ubuntu-package-18.04
    resource_class: large

  ubuntu_publish:
    docker:
      - image: ubuntu:bionic
    environment:
      LANG: C.UTF-8
    steps:
      - checkout
      - run: apt-get update -q && apt-get install -q -y ca-certificates openssh-client
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$' VERSION && export DEB_COMPONENT=main || export DEB_COMPONENT=dev
            scp -P $SSH_PORT -o StrictHostKeyChecking=no /tmp/workspace/geotrek-admin_*_amd64.deb $SSH_USER@$SSH_HOST:/srv/packages/incoming/$DEB_COMPONENT/
      - run: ssh -p $SSH_PORT -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST make -C
          /srv/packages
    resource_class: large

workflows:
  version: 2
  all:
    jobs:
      - codestyle:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - doc:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_image:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_image_18_04:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test:
          requires:
            - docker_image
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test_18_04:
          requires:
            - docker_image_18_04
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test_nds:
          requires:
            - docker_image
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test_nds_18_04:
          requires:
            - docker_image_18_04
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test_js:
          requires:
            - docker_image
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_test_integration:
          requires:
            - docker_image
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - docker_publish:
          requires:
            - codestyle
            - docker_test
            - docker_test_nds
            - docker_test_js
            - docker_test_integration
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - ubuntu_package:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - ubuntu_package_18_04:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - ubuntu_publish:
          requires:
            - codestyle
            - ubuntu_package
            - ubuntu_package_18_04
            - docker_test
            - docker_test_18_04
            - docker_test_nds
            - docker_test_nds_18_04
            - docker_test_js
            - docker_test_integration
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
