name: Check deps

on:
  pull_request:
    paths:
      - pyproject.toml.py
      - requirements.txt
      - dev-requirements.txt
      - docs/requirements.txt
      - .github/workflows/dependencies.yml

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  quality:
    name: Checking dependency graph
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: ./.github/actions/python-cache-requirements
        with:
          requirements: dev-requirements.txt

      - name: Install dependencies
        run: |
          pip install uv

      - name: Check dependency graph
        run: |
          make ci_check_deps

      - name: Verify dependency graph is ok
        uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          files: |
            requirements.txt
            dev-requirements.txt
            docs/requirements.txt

      - name: Validating graph
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Dependency file(s) changed: ${{ steps.verify-changed-files.outputs.changed_files }}"
          git diff
          core.setFailed('Please add your new dependencies in setup.py and/or dev-requirements.in then run pip-compile to add them in requirements. (see docs/contribute/development)')
