name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
  release:
    types:
      - created

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  doc:
    name: Doc structure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/python-cache-requirements
        with:
          requirements: docs/requirements.txt

      - name: Build doc
        run: |
          cd docs/
          make html SPHINXOPTS="-W"

      - name: Check translations build
        run: |
          cd docs/
          make gettext
          sphinx-intl update -l fr
          sphinx-intl build
          sphinx-build -b html -D language='fr' -d _build/doctrees . _build/html/fr

      - name: Check missing translations
        uses: tj-actions/verify-changed-files@v17
        id: verify-changed-files
        with:
          files: |
             docs/**.po

      - name: Check no translation file has changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Translation file(s) changed: ${{ steps.verify-changed-files.outputs.changed_files }}"
          git diff
          core.setFailed('Please update doc translation y running `make gettext` and `sphinx-intl update -l fr`, then fix or update translation, and commit the changes.')

