name: Linting

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  flake8:
    name: Check code styling
    runs-on: ubuntu-latest
    container:
      image: python:3.6

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install flake8

      - name: Flake8
        run: |
          flake8 geotrek

      - name: Not evaluated values in migration files
        run: |
          test $(ls geotrek/*/migrations/*.py | xargs grep -l srid | xargs grep -L SRID | wc -l) -eq 0
